import { BACKEND_API_KEY, BACKEND_URL, isBackendConfigured } from '../config/backend';
import { FCRA_CONSENT_BODY } from '../legal/disclaimers';
import { getRequesterId } from './subscriptions';

/**
 * Background-check client. All CRA traffic is routed through OUR backend proxy
 * (`backend/`) — the mobile app never holds the provider's API key. The
 * backend records the FCRA consent, calls the CRA, and returns a report id
 * the app can poll.
 *
 * When the backend URL/key isn't set, the client falls back to a mock so the
 * UI stays testable during development.
 */

export interface BackgroundCheckRequest {
  firstName: string;
  lastName: string;
  email?: string;
  dateOfBirth?: string;
  /** Confirmation that the FCRA disclosure was shown and consent obtained. */
  consentConfirmed: boolean;
  purpose: 'employment' | 'tenant' | 'volunteer' | 'other';
}

export interface BackgroundCheckRecord {
  type: 'warrant' | 'criminal' | 'court' | 'traffic' | 'other';
  jurisdiction?: string;
  description: string;
  date?: string;
}

export type BackgroundCheckStatus =
  | 'pending'
  | 'clear'
  | 'consider'
  | 'complete'
  | 'suspended'
  | 'error';

export interface BackgroundCheckResult {
  reportId: string;
  status: BackgroundCheckStatus;
  records: BackgroundCheckRecord[];
  disclaimer: string;
}

const DEV_DISCLAIMER =
  'DEV MODE — backend URL/key not configured. Set `expo.extra.backendUrl` and ' +
  '`backendApiKey` in app.json to hit the CRA proxy for real reports.';

const REAL_DISCLAIMER =
  'Report generated by a third-party consumer reporting agency via our secure ' +
  'backend. Data accuracy is not guaranteed and may be incomplete. Use only for ' +
  'purposes disclosed and consented to by the subject.';

export async function runBackgroundCheck(
  req: BackgroundCheckRequest,
): Promise<BackgroundCheckResult> {
  if (!req.consentConfirmed) {
    throw new Error('FCRA consent must be confirmed before running a report.');
  }
  if (!isBackendConfigured()) {
    await new Promise((r) => setTimeout(r, 600));
    return {
      reportId: `mock_${Date.now()}`,
      status: 'pending',
      records: [],
      disclaimer: DEV_DISCLAIMER,
    };
  }

  const requesterId = await getRequesterId();
  const res = await fetch(`${BACKEND_URL}/v1/background-checks`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-Api-Key': BACKEND_API_KEY,
      'X-Requester-Id': requesterId,
    },
    body: JSON.stringify({
      subject: {
        firstName: req.firstName,
        lastName: req.lastName,
        email: req.email,
        dateOfBirth: req.dateOfBirth,
      },
      purpose: req.purpose,
      consent: {
        signedAt: new Date().toISOString(),
        disclosureText: FCRA_CONSENT_BODY,
      },
    }),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`Background check failed (${res.status}): ${text || res.statusText}`);
  }

  const body = (await res.json()) as {
    reportId: string;
    status: BackgroundCheckStatus;
    records: BackgroundCheckRecord[];
  };

  return {
    reportId: body.reportId,
    status: body.status,
    records: body.records ?? [],
    disclaimer: REAL_DISCLAIMER,
  };
}

export async function fetchBackgroundCheck(reportId: string): Promise<BackgroundCheckResult> {
  if (!isBackendConfigured()) throw new Error('Backend not configured.');
  const requesterId = await getRequesterId();
  const res = await fetch(
    `${BACKEND_URL}/v1/background-checks/${encodeURIComponent(reportId)}`,
    {
      headers: { 'X-Api-Key': BACKEND_API_KEY, 'X-Requester-Id': requesterId },
    },
  );
  if (!res.ok) throw new Error(`Failed to fetch report: ${res.status}`);
  const body = (await res.json()) as {
    reportId: string;
    status: BackgroundCheckStatus;
    records: BackgroundCheckRecord[];
  };
  return {
    reportId: body.reportId,
    status: body.status,
    records: body.records ?? [],
    disclaimer: REAL_DISCLAIMER,
  };
}
